name: CI Pipeline for .NET application

on:
  push:
    branches:
    - '*'

jobs:
  build:
    uses: ./.github/workflows/dotnet-build-test.yml
    with:
      solution-path: 'ECU_Replica/ECU_Replica.sln'
      dotnet-version: 'v4.8'
